### PR TITLE
support schema operations

### LINKED ISSUE #145: PostgreSQL: Referencing data on another schema
First of all sry due to English not being my first language.

Am I able to do REFERENCES ,JOINS and other operations in between schemas with this framework?
 I´m trying to wrap my head around it but I can only create tables in different schemas using this bit of code just before the create operation

`fun Transaction.setSchema(schema: DatabaseSchemas){
        exec("set SEARCH_PATH TO \"$schema\"")
    }`

`transaction {
            setSchema(DatabaseSchemas.XXXXXXX)
            createMissingTablesAndColumns(UsersTable)
        }`

where DatabaseSchemas is an Enum of all My Schemas (done this way for ease of use)

### PR DESCRIPTION
**Pull request by hichem-fazai**
Fixes #145 , #254 and #803
This PR is to support shemas creation,cross-joins from different schemas and make selects from different schemas. also make all operations(selects, drops and updates)  with specific schema . Some examples of use

````Kotlin

/** create two schemas  */
SchemaUtils.createSchema(Schema("schema1"))
SchemaUtils.createSchema(Schema("schema2"))

/** create tables in schemas */
val author = Author.withSchema(schema1)
val book = Book.withSchema(schema2, author)
SchemaUtils.create(author)
SchemaUtils.create(book)

/** insert in Author table from schema1  */
Author.insertInSchema(schema1) {
    it[name] = "author-name"
}

/** you can also use author.insert {} directly or Author.withSchema(schema1).insert{} */
author.insert {
    it[Author.name] = "author2-name"
}

/** test inner-joins from different schemas  */
(Author.withSchema(schema1) innerJoin Book.withSchema(schema2)).slice(Book.id, Author.id).selectAll().forEach {
    println("${it[Author.id]} wrote ${it[Book.id]}")
}

/** test cross-joins from different schemas  */
(Author.withSchema(schema1) crossJoin Book.withSchema(schema2)).slice(Book.id, Author.id).selectAll().forEach {
    println("${it[Author.id]} wrote ${it[Book.id]}")
}

/** same thing for right and left joins */

/** you can use author and book objects directly  */
(author innerJoin book).slice(Book.id, Author.id).selectAll().forEach {
    println("${it[Author.id]} wrote ${it[Book.id]}")
}

val authorSchema = Author.withSchema(schema1)

/** update table with schema. */
authorSchema.update({ Author.name eq "author1" }) {
    it[Author.name] = "author"
}

/** delete from table with schema. */
authorSchema.deleteWhere {
    Author.name eq "hichem"
 }
    
object Author : IntIdTable("authork") {
    val name = varchar("name", 20)
}

object Book : Table("bookk") {
    val id = integer("id")
    val authorId = reference("authorId", Author).nullable()

    override val primaryKey = PrimaryKey(id)
}

````
This PR could be a first step to resolve - #795

### CODE REVIEW

**Comment by hichem-fazai** [comment]
Also, you can optionally specify the "authorization" parameter when creating schema : 
````kotlin
val schema = Schema (name = "schema1",
                     authorization = "root")

SchemaUtils.createSchema(schema)

//To drop
SchemaUtils.dropSchema(schema )

**Comment by Tapac** [comment]
Hi, thank you for a PR. I have some ideas and suggestions.
Do you registered on kotlin slack? It will be a bit faster to discuss short questions there.
You could find me (tapac) at kotlinlang.slack.com. 

If you could not/won't use slack I will share my thoughts there

**Comment by hichem-fazai** [comment]
> Hi, thank you for a PR. I have some ideas and suggestions.

Great 🎉 I already inspired it from your last suggestions. And tell me if you have any change requests or improvements 😉 

> Do you registered on kotlin slack? It will be a bit faster to discuss short questions there.
> You could find me (tapac) at kotlinlang.slack.com.

I'm not registred but it would be great to do that. Do I need to have an email (@jetbrains.com) to register to kotlin slack? (I'm not very familiar with slack 😄) . I tried to join kotlinlang workspace but it tells me to use @jetbrains.com mail to register

**Comment by Tapac** [comment]
I sent you an invitation.

**Comment by hichem-fazai** [comment]
Closed, should be done with another design.

**Pull request closed without merging**
