### PR TITLE
Fixed limitation of AutoInc. column's

### PR DESCRIPTION
**Pull request by fhntv24**
Fix for #31
Auto inc. column could be only of type int, because you couldn't get created id with InsertStatement

Tested with long column type
Test code:
```kotlin
    transaction {
            create(TestTable)
            println(TestTable.insert { it[TestTable.UserUUID] = 1000000 } get TestTable.UserUUID)
            //This will increase AutoInc counter to 2^34
            println(TestTable.insert { it[TestTable.UserUUID] = 1.toLong() shl 34 /*2 to the power of 34. Constant one would be Int for some reason ...*/ } get TestTable.UserUUID)
            println(TestTable.insert { } get TestTable.UserUUID)
            drop(TestTable)
        }
```

Sample output:
1000000
17179869184
17179869185

### CODE REVIEW

**Comment by fhntv24** [comment]
Also i have fixed some issues releated to schemas - right now you can use only default schema that is in SQL connector url.
Is it necesery to pull request that changes too? There actually a lot of them, it was broken in a few parts of library

**Comment by Tapac** [comment]
@fhntv24 
Thank you for PR, I will review it some later.
About support for different schemas - I think it's cool feature and I will glad to look at your PR.

**Comment by fhntv24** [comment]
Also i wanted to work for supporting expressions as defaul values, as i need it for my project too. I will see if i can PR it, as there also other changed that may be only for myself

**Comment by Tapac** [comment]
We fixed it in more generic way for IdTables (see insertAndGetId function), so I close your PR, but thank you anyway.

**Pull request closed without merging**
