### PR TITLE
add afterStatementPrepared method to StatementInterceptor

### PR DESCRIPTION
**Pull request by lure**
Slightly enrich the the existing StatementInterceptor by adding `afterStatementPrepared`

### CODE REVIEW

**Comment by lure** [comment]
@AlexeySoshin 
to add engine-specific clauses to prepared statement. Think lock predicates etc

**Comment by Tapac** [comment]
@lure , do you mean "add" through accessing underling `JdbcPreparedStatementImpl.statement` and using JDBC `PreparedStatement`?

Can you please share a more detailed example as it looks not very convenient and maybe we can define find about another aporach?

**Comment by lure** [comment]
```kotlin
class TXLifetimeInterceptor(private val lifetime: Lifetime) : StatementInterceptor {

    @Volatile
    private var currentRunningQuery: PreparedStatementApi? = null

    init {
        lifetime.addOrCallImmediately {
            currentRunningQuery?.let {
                try {
                    UnsafeBlocking.executeBlocking {
                        it.cancel()
                    }
                } catch (e: Exception) {
                    log.warn(e) { "Unable to cancel running query" }
                }
            }
        }
    }

    override fun afterStatementPrepared(transaction: Transaction, preparedStatement: PreparedStatementApi) {
        currentRunningQuery = preparedStatement
        validateLifetime()
    }

    override fun afterExecution(
        transaction: Transaction,
        contexts: List<StatementContext>,
        executedStatement: PreparedStatementApi,
    ) {
        currentRunningQuery = null
        validateLifetime()
    }

    private fun validateLifetime() {
        if (lifetime.isTerminated) {
            throw CancellationException("Transaction lifetime was terminated")
        }
    }
}

```
@Tapac 
@AlexeySoshin 

> do you mean "add" through accessing underling JdbcPreparedStatementImpl.statement and using JDBC PreparedStatement?

Among other usages, yes.

**Comment by lure** [comment]
@joc-a  @bog-walk  ^^

**Comment by bog-walk** [comment]
@lure Hi, I'm currently reviewing the use case for this PR, as well as #1621, where I've already left a comment for you. It won't be long now.

**Pull request merged**
