### PR TITLE
Remove unnecessary parentheses for functions

### PR DESCRIPTION
**Pull request by Maxr1998**
Fix for #1486.

### CODE REVIEW

**Review by favelado-web — APPROVED** [review]

**Review by bog-walk — COMMENTED** [review]
@Maxr1998 Thank you for submitting this PR.

In the effort of improving test coverage, even as a one-line change, could you please include a test in `DefaultsTest.kt` in both modules `exposed-kotlin-datetime` & `exposed-java-time`? Something like this:

```kt
@Test
fun testAddMissingColumnStatementsWithDefaultExpression() {
    val testTable = object : IntIdTable("test_table") {
        val name = varchar("name", 128)
        val createdAt = datetime("created_at").defaultExpression(CurrentDateTime)
    }

    withDb {
        try {
            SchemaUtils.create(testTable)
            val actual = SchemaUtils.statementsRequiredToActualizeScheme(testTable)

            assertTrue(actual.isEmpty())
        } finally {
            SchemaUtils.drop(testTable)
        }
    }
}
```

**Comment by Maxr1998** [comment]
Sure, can do! I'll get to it in the next few days.

**Comment by Maxr1998** [comment]
Those tests were more than appropriate because the original code was doing absolutely nothing. The `Function` that I checked against was `kotlin.Function`, not the expected `org.jetbrains.exposed.sql.Function`. I think star imports are quite dangerous in cases like these, and I suggest disabling them for this project.

**Review by bog-walk — APPROVED** [review]
Thanks for including the tests, and for pointing out the potential pitfall re enabling start imports.

**Review by e5l — APPROVED** [review]

**Pull request merged**
