### PR TITLE
fix: Crash in use of aliased OpBoolean

### PR DESCRIPTION
**Pull request by daemon23**
Selecting aliased comparison results blows up (in mariadb/mysql, anyway) trying to cast an int to a boolean. This corrects that issue.

### CODE REVIEW

**Comment by daemon23** [comment]
After fussing with the code I have an alternative which would simplify this significantly, but it involves restructuring Expression and ExpressionWithColumnType to be interfaces; I can easily see it being a breaking change for users.

**Comment by Tapac** [comment]
Thank you for a PR. I think it would be better to resolve it in a more generic way for all ExpressionAliases by making a recursive call to `rawToColumnValue` with delegate as a value. WDYT?

**Comment by daemon23** [comment]
That actually makes a lot of sense as well. It might be worth performing a check in ExpressionAlias's init block that the delegate is not itself an alias; the only downside I could think of is some sort of bizarre multiple nesting aliases scenario, but I can't think of an SQL where that would be legal anyway.

**Comment by daemon23** [comment]
btw just want to note that I really like what you've done here--I'm just sorry that I probably can't use it in my job because we have a number of devs who are opposed to any ORM tool that doesn't prioritize working with raw SQL.

**Comment by joc-a** [comment]
> Thank you for a PR. I think it would be better to resolve it in a more generic way for all ExpressionAliases by making a recursive call to `rawToColumnValue` with delegate as a value. WDYT?

@Tapac Something like this?

```
@Suppress("UNCHECKED_CAST")
    private fun <T> rawToColumnValue(raw: T?, expression: Expression<T>): T {
        return when {
            raw == null -> null
            raw == NotInitializedValue -> error("$expression is not initialized yet")
            expression is ExpressionAlias<T> && expression.delegate is ExpressionWithColumnType<T> -> expression.delegate.columnType.valueFromDB(raw)
            expression is ExpressionWithColumnType<T> -> expression.columnType.valueFromDB(raw)
            expression is Op.OpBoolean -> BooleanColumnType.INSTANCE.valueFromDB(raw)
            expression is ExpressionAlias<T> -> rawToColumnValue(raw, expression.delegate)
            else -> raw
        } as T
    }
```

**Pull request closed without merging**
