### PR TITLE
Add support for datetime with timezone 

### PR DESCRIPTION
**Pull request by alsofr**
Introduce a separate new datetimetz type

Existing datetime field was left untouched to avoid backward incompatibilities issues.

MySQL doesn't actually have support for the type so a dummy/incomplete implementation was done.

### CODE REVIEW

**Comment by alsofr** [comment]
retest

**Comment by alsofr** [comment]
HI there, I googled how to retrigger a new pipeline in Teamcity after adding a new commit to my existing pull request but it doesn't seem to work.
The original build failed (but works locally) and I can't find any useful information in the logs (which database causes it to fail?).
@Tapac is this possible or do I need to create a new pull request every time I have changes?
Thanks in advance.

Early comments on the PR welcome as well.

**Comment by Tapac** [comment]
Hi @alsofr , the build will be triggered automatically after Teamcity will see your changes and free agent is available.

As I can see from the build log the ":exposed-java-time:test" task fails with `Invalid zone offset pattern: +HH:mm:ss` exception. 
You can try to run that task locally and check will it pass or not.

**Comment by alsofr** [comment]
Thanks for your answer, the build indeed retriggered, but several hours later.

I'm suspecting a difference between h2 running on mac osx vs linux because _it works on my machine_ ™️ :).

**Comment by alsofr** [comment]
Hi again @Tapac , 12 hours later and still no build triggered for my 2 new commits. Is that expected?

**Comment by Tapac** [comment]
I've run build and reinstall GitHub webhook, I hope it will help.

**Comment by alsofr** [comment]
@Tapac the issue with TeamCity persists, the new commit doesn't trigger a new pipeline run in Teamcity.

**Comment by alsofr** [comment]
Hi there, a review would be appreciated.
@Tapac maybe ?

**Comment by alsofr** [comment]
Hi again, sorry to insist but could i get a review on this code please? @Tapac ?

**Comment by tim-fdc** [comment]
HI @Tapac ,
 any news about this PR? We really need more time support.
 Best
 Tim

**Comment by dvorsky** [comment]
any update on this? why wasnt it merged? DateTime with TimeZone is really common feature  @Tapac

**Comment by joc-a** [comment]
Hey @alsofr. Thank you for your contribution. This feature has now been implemented here #1787.

**Pull request closed without merging**
