### PR TITLE
#253 Add support to delete with limit and offset

### PR DESCRIPTION
**Pull request by Mon-chi**

### CODE REVIEW

**Comment by Tapac** [comment]
I advise you to change the order of `deleteWhere/deleteIgnoreWhere` functions to keep delete condition the last one. Overwise it could break existing code, also in most cases, you don't want to use limit/offset, but only where condition and in that case, you will need to use additional brackets:
` FooTable.deleteWhere({ FooTable.id eq 1 }) `

**Comment by Tapac** [comment]
May I also ask you to add simple DML test with using limit and offset params to be sure that it works as expected on every DBMS?

**Comment by Mon-chi** [comment]
Is this all right?

**Comment by Tapac** [comment]
Still failing https://teamcity.jetbrains.com/viewLog.html?buildId=1392843&tab=buildResultsDiv&buildTypeId=Exposed_PullRequests
`java.lang.AssertionError: Failed on h2 expected:<1> but was:<3>`

**Comment by Tapac** [comment]
Looks like PostgreSQL doesn't support LIMIT/OFFSET at all: https://www.postgresql.org/docs/9.3/static/sql-delete.html
There are different workarounds for it: https://stackoverflow.com/questions/5170546/how-do-i-delete-a-fixed-number-of-rows-with-sorting-in-postgresql

**Pull request merged**
