### PR TITLE
build: Add dependencies to Version Catalog

### PR DESCRIPTION
**Pull request by pank-su**
As Exposed is a multi-project solution on Gradle, we encountered issues with using the same versions for dependencies in different places. To address this, I re-wrote all dependencies using Version Catalog.

### CODE REVIEW

**Review by e5l — CHANGES_REQUESTED** [review]
Could you please check the build? 

It fails with:
```
org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to an object of type Dependency: io.gitlab.arturbosch.detekt:1.23.3.
The following types/formats are supported:
  - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
  - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
  - FileCollections, for example files('some.jar', 'someOther.jar').
  - Projects, for example project(':some:project:path').
  - ClassPathNotation, for example gradleApi().

Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
4 actionable tasks: 4 executed
```

**Comment by e5l** [comment]
Could you please check the CI:
```
:exposed-spring-boot-starter:testOracle
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24266_24266&logFilter=important&logView=flowAware)      e: file:///mnt/agent/work/659d3358fdd5763d/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/QueryTimeoutTest.kt:4:12 Unresolved reference: microsoft
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24267_24267&logFilter=important&logView=flowAware)      e: file:///mnt/agent/work/659d3358fdd5763d/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/QueryTimeoutTest.kt:91:67 Unresolved reference: SQLServerException
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24269_24269&logFilter=important&logView=flowAware)      OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24270_24270&logFilter=important&logView=flowAware)      OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24271_24271&logFilter=important&logView=flowAware)      OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24272_24272&logFilter=important&logView=flowAware)      OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24273_24273&logFilter=important&logView=flowAware)      e: file:///mnt/agent/work/659d3358fdd5763d/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/QueryTimeoutTest.kt:4:12 Unresolved reference: microsoft
[08:22:15 ](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/3438?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=3438_24274_24274&logFilter=important&logView=flowAware)      e: file:///mnt/agent/work/659d3358fdd5763d/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/QueryTimeoutTest.kt:91:67 Unresolved reference: SQLServerException
```

You can also log in there as a guest

**Comment by pank-su** [comment]
Oh, please forgive me for wasting your time.

**Review by e5l — APPROVED** [review]
Thanks for the PR. LGTM

**Pull request merged**
