### PR TITLE
feat: EXPOSED-295 Support subqueries with preceding LATERAL

### PR DESCRIPTION
**Pull request by obabichevjb**
Here is the support of LATERAL joins (such a join allows using inside the joining query previous joining parts [Postgres, 7.2.1.5. LATERAL Subqueries](https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL))

With this MR it's possible to mark `JoinPart` as `lateral` and it will add the key word to join operator.

The downside of the solution is that any `JoinPart` can be marked as lateral, event if it makes sense only for joining queries. It could be possible to avoid it if we split non-query-join and query-join somewhere on `ColumnSet` level which has only one `ColumnSet::join()` method now. It does not look reasonable to me, but it's discussable.

Also minor change, `on` condition of `joinQuery()` is optional now because it's possible to join a query without condition (at least for CROSS join).

### CODE REVIEW

**Review by bog-walk — COMMENTED** [review]
If `lateral` is only used in `JoinPart` with subqueries, then something like this is not valid right? When I run it, the LATERAL keyword is just ignored and not included in generated SQL:
```kt
tester1.crossJoin(tester2, lateral = true).selectAll()
```

If so, I agree then that we should not include it in the API, at least where we can avoid it. I'd suggest removing the new parameter from all the named join functions and setting always to `false`, for example:
```kt
fun <C1 : ColumnSet, C2 : ColumnSet> C1.crossJoin(
    otherTable: C2,
    onColumn: (C1.() -> Expression<*>)? = null,
    otherColumn: (C2.() -> Expression<*>)? = null,
    additionalConstraint: (SqlExpressionBuilder.() -> Op<Boolean>)? = null,
): Join = join(otherTable, JoinType.CROSS, onColumn?.invoke(this), otherColumn?.invoke(otherTable), false, additionalConstraint)
```

So the only places with access to `lateral` would be:
- Table.join()
- Table.joinQuery()
- Join.joinQuery()
- QueryAlias.join()

Which I believe would all allow valid uses of LATERAL since they accept either subqueries or subquery aliases.

**Comment by obabichevjb** [comment]
> If `lateral` is only used in `JoinPart` with subqueries, then something like this is not valid right? When I run it, the LATERAL keyword is just ignored and not included in generated SQL:
> 
> ```kotlin
> tester1.crossJoin(tester2, lateral = true).selectAll()
> ```

Actually it's a bug, I'd say… because it's possible to call `crossJoin` with query alias like this:

```kotlin
val subqueryAlias = tester2.selectAll().where { tester2.value greater tester1.value }.limit(1).alias("subquery")

// cross join (can be without condition)
val query = tester1.crossJoin(subqueryAlias, lateral = true)

// or left join (condition must be defined)
val query = tester1.leftJoin(subqueryAlias, lateral = true, onColumn = { tester1.id }, otherColumn = { subqueryAlias[tester2.tester1] })
```

I will fix it, but it looks like lateral makes sense in more places that I expected.

I thought that joining queries can be made only via `joinQuery()`, but looks like actually not.

**Comment by obabichevjb** [comment]
Updated PR:
- fix implicit joins, it can also be lateral
- remove lateral parameter from leftJoin, crossJoin and so on. It should make api cleaner. If the user needs lateral join, he can still use full `join(table, type, onColumn, otherColumn, lateral)` call.
- added validation that `lateral` is not used with `Table` to throw an error on query construction step.

**Review by bog-walk — APPROVED** [review]

**Comment by dauid64** [comment]
@bog-walk @obabichevjb

I am trying to write a query with a lateral join, but I can't find any documentation for this method. Could anyone provide an example of how to write a query using a lateral join?

In my case, I am trying to implement this SQL query using Exposed:
```sql
SELECT j.id
FROM jornadas j
JOIN LATERAL (
     SELECT p.cod, p.data_criacao
     FROM passos p
     WHERE p.jornada_id = j.id
     ORDER BY p.data_criacao DESC, p.id DESC
     LIMIT 1
) last ON last.data_criacao <= NOW() - INTERVAL '10 minutes'
AND last.cod NOT IN ('FINAL','ENCERRADA')
```

**Pull request merged**
