### PR TITLE
Move documentation to the "docs" folder

### PR DESCRIPTION
**Pull request by Shpota**
I moved all documentation-related files (5 `.md` files and the logo) from the root of the repository to the `docs` folder.

**Why you might want to consider these changes:**
- The repository looks cleaner, shorter and more friendly for new users.
- The documentation files are separated from the source code.
- It is a standard folder of a GitHub repository. GitHub finds README files automatically in this folder.
- Check what it looks after the changes [in my fork of the project](https://github.com/Shpota/Exposed/tree/restructure-documentation).

### CODE REVIEW

**Comment by qoomon** [comment]
I think you should use a dedicated `doc` or `documentation` folder.
Documentation shouldn't be within a hidden folder :-D, especially not in github service related folder.

**Comment by Shpota** [comment]
@qoomon good idea, thank you. GitHub also [supports](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes) `docs` folder as a default README location. I have moved the files there.

**Comment by qoomon** [comment]
@Shpota oh cool I wasn't aware of `docs` folder feature, thx for noticing.

**Comment by Tapac** [comment]
Thank you for a PR, it's much cleaner now.

**Pull request merged**
