### PR TITLE
fix!: EXPOSED-269 Incompatible with sqlite-jdbc 3.45.0.0

### PR DESCRIPTION
**Pull request by joc-a**
sqlite-jdbc 3.45.0.0 [reintroduced improved support for `Statement#getGeneratedKeys()`](https://github.com/xerial/sqlite-jdbc/commit/f7d49f63172462c810219a7b53f5c0e667e11ce8), but the implementation is different from the previous implementation and does not work with Exposed. This is a temporary workaround to fix the crash caused by that until we figure out how we're supposed to use sqlite-jdbc 3.45.0.0+ with Exposed.

### To be investigated ([YouTrack issue](https://youtrack.jetbrains.com/issue/EXPOSED-328)):
The problem is that a newly-introduced function `Statement#updateGeneratedKeys()` in sqlite-jdbc, which sets the value of the ResultSet, is not invoked when `executeBatch()` is used, but only with `executeUpdate()`. This means that something probably has to be changed in the following function in InsertStatement.kt in Exposed to accommodate this new behaviour:
```
protected open fun PreparedStatementApi.execInsertFunction(): Pair<Int, ResultSet?> {
    val inserted = if (arguments().count() > 1 || isAlwaysBatch) executeBatch().sum() else executeUpdate()
    val rs = if (autoIncColumns.isNotEmpty()) {
        resultSet
    } else {
        null
    }
    return inserted to rs
}
```

### CODE REVIEW

**Review by bog-walk — APPROVED** [review]
Just confirming that these changes won't work with the older SQLite version, right? So bumping to the upcoming Exposed version would mean needing to bump SQLite too?

**Review by e5l — APPROVED** [review]

**Comment by joc-a** [comment]
> Just confirming that these changes won't work with the older SQLite version, right? So bumping to the upcoming Exposed version would mean needing to bump SQLite too?

@bog-walk That's correct. Should we add a note about this under Breaking Changes or just mention it in the GitHub release description?

**Comment by bog-walk** [comment]
I'd include a note wherever gets the most visibility to users, just to be safe, so I'd probably go for the breaking changes section in the changelog.

**Comment by JordanPlayz158** [comment]
Glad to see this is documented, just got burned by this so can't wait for this to get this fix pushed and included in next release. The docs gave me a clue because it had specific versions pinned luckily so I went, to heck with it and tried, thank goodness it worked, would've been pulling my hair out for hours

**Pull request merged**
