### PR TITLE
Replace copying arraylists w/ concurrent queues

### PR DESCRIPTION
**Pull request by jnfeinstein**
Writing to the list of events is a common occurrence, which currently results in the creation of an entire array of existing events, an O(n^2) operation.  Using a concurrent queue should reduce the footprint of this operation.

Extracted backwards-compatible change from #1133.

### CODE REVIEW

**Comment by Tapac** [comment]
Can you please explain why it is O^2 on ArrayList? Afaik add and get is O(1).

**Comment by jnfeinstein** [comment]
Appending to `ArrayList` is O(1) when the backing array has capacity, and incurs a resize penalty when there is not.  If you're optimizing for appending and removing from a list in order (e.g. basic queue), the better option is to use `LinkedList`, as it is always O(1) to append.  However in this case the structure is a `CopyOnWriteArrayList`.  This allocates a new array every time a new event is appended.  To append the nth event you have to allocate an array of size n, and copy n-1 items.  This has been done for every event prior, which is probably more geometric in efficiency than O(n^2) but I've forgotten that part of the textbook.

I believe the correct use case for a `CopyOnWriteArrayList` is when you are frequently reading and infrequently writing.  The provided dequeue should be optimal for this scenario.

**Comment by Tapac** [comment]
My bad, I look into code via mobile GitHub app and doesn't see that it was CopyOnWriteArrayList;)

**Comment by jnfeinstein** [comment]
Should see a significant performance improvement from this one.  Now on to tackle the `EntityCache`...😄

**Pull request merged**
