### PR TITLE
Polish long query logging.

### PR DESCRIPTION
**Pull request by neetkee**
* Use monotonic time.
* Remove empty RuntimeException() for warn message.

### CODE REVIEW

**Comment by Tapac** [comment]
If you'll remove RuntimeException the stacktrace will be inaccessable in the log.

**Comment by neetkee** [comment]
It is worth to add a custom exception class at least?

**Comment by Tapac** [comment]
@neetkee , I don't mind. It can be ExposedSQLException, for example. Can you change it in your PR?

**Comment by neetkee** [comment]
As I can see, `ExposedSQLException` throws only on SQL errors right now.  It also contains some logic behind queries, which is already logged within `warn` message. I've added new `LongQueryException`, hope it's okay.

**Pull request merged**
