### PR TITLE
Sum batch results for inserts

### PR DESCRIPTION
**Pull request by johnzeringue**
When executing a batch insert, the number of inserted rows is the sum of the batch rows instead of the count.

Making this distinction allows extensions of batch insert like
```kotlin
class MyBatchInsertStatement(
    table: Table,
) : BatchInsertStatement(table) {
    override fun prepareSQL(transaction: Transaction) = buildString {
        append(super.prepareSQL(transaction))
        append(" ON CONFLICT (id) DO NOTHING")
    }
}
```
where the return value of `execute` is still accurate.

### CODE REVIEW

**Comment by johnzeringue** [comment]
Added a unit test. Now that the repo is more active, I'd appreciate help getting this reviewed and over the finish line 🙂

**Comment by johnzeringue** [comment]
@bog-walk could you please review?

**Review by bog-walk — COMMENTED** [review]
Thank you for bringing to our attention that the count of batch inserted rows was being calculated incorrectly. Running new tests, I can see how this returns a more accurate value when inserts are ignored.

A quick update as I'm looking more into this PR ->

The issue I'm trying to resolve is: if your custom class is altered, for example, to be a `BatchInsertUpdateOnDuplicate`, the returned affected-row values might differ from 1 or 0 (especially in MySQL - explained with links in [this issue](https://github.com/JetBrains/Exposed/issues/129)).

In fact, looking through the [commit history](https://github.com/JetBrains/Exposed/commit/14eaa5a7781f07762e8e6bd034f496e0499c4d1c), the changed line used to be `executeBatch().sum()` but was switched many years ago. I need to look more into why & what our options are to ensure that all end-user custom functions can be properly supported.

Maybe it would make sense to remove batch business logic from the `InsertStatement` class and override `execInsertFunction` in `BaseBatchInsertStatement` instead, or even create a MySQL-specific class extension.

**Comment by johnzeringue** [comment]
The MySQL use case is interesting, but I think the `sum()` behavior is more accurate there too.
```sql
mysql> CREATE TABLE t1 (a INTEGER UNIQUE, b INTEGER, c INTEGER);
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO t1 (a,b,c) VALUES (1,2,3)
    ->   ON DUPLICATE KEY UPDATE c=c+1;
Query OK, 1 row affected (0.04 sec)

mysql> INSERT INTO t1 (a,b,c) VALUES (1,2,3)   ON DUPLICATE KEY UPDATE c=c+1;
Query OK, 2 rows affected (0.00 sec)

mysql> SELECT * FROM t1
    -> ;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    1 |    2 |    4 |
+------+------+------+
1 row in set (0.01 sec)

mysql> INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6)
    ->   ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);
Query OK, 3 rows affected, 2 warnings (0.01 sec)
Records: 2  Duplicates: 1  Warnings: 2
```

**Comment by bog-walk** [comment]
I agree that it is more accurate, but it could potentially be misleading due to the naming choice if a batch of 1 insert & 1 update (as in your example) for a single row results in `insertedCount = 3` by way of `PreparedStatementApi.executeInternal()`.

If anything, there should probably be a second property `affectedCount`, which would more appropriately hold the summed value.

Here's what I'm thinking -> We're working on supporting upsert and `BatchUpsertStatement` out of the box, so we'll consider placing that new property in the new class and overriding `execInsertFunction()` there to handle the distinction between the two counts. And we'll go forward with this fix.

**Review by bog-walk — APPROVED** [review]

**Comment by johnzeringue** [comment]
@e5l friendly bump

**Review by e5l — APPROVED** [review]

**Pull request merged**
