### PR TITLE
Support custom enum parsing when reading from the database

### PR DESCRIPTION
**Pull request by davidpodhola**
Inspired by https://stackoverflow.com/a/46303600/2013924. Please also see #191. Works on Postgres.

### CODE REVIEW

**Comment by Tapac** [comment]
Hello, thank you for PR, but I have some questions:
1. Do you test that this approach works fine in both directions? I mean when you try to write an Enum value to a database will it be stored properly?
2. Don't you mind to declare `handle` function `(Any) -> T to force users to resolve it into Enum?

**Comment by davidpodhola** [comment]
Hi, thanks for commenting on my PR.

1. I think parameter needs to be send as `String` and a `CAST` is needed inside the SQL, I already send JSON this way (see also [Convert between Java enums and PostgreSQL enums](http://www.gotoquiz.com/web-coding/programming/java-programming/convert-between-java-enums-and-postgresql-enums/)); would you please help me to find where to add the CAST in INSERT and UPDATE?
2. done + changed the name.

**Comment by Tapac** [comment]
After discussion with my colleagues, we decided that extending existing `enumerationByName` is not very convenient, so I added `customEnumeration` function (see that commit [8d1f31f](https://github.com/JetBrains/Exposed/commit/8d1f31f9ed1f247466d5050913bf28827bd89590) and test as the example).

I'll close you PR, but thank you for an inspiration:D

**Comment by Tapac** [comment]
[](url)

**Comment by davidpodhola** [comment]
Thanks, this looks very nice, will be happy to use your version.

**Pull request closed without merging**
