### PR TITLE
Support unions of queries

### PR DESCRIPTION
**Pull request by jnfeinstein**

### CODE REVIEW

**Comment by Tapac** [comment]
Thank you for a PR. 
From the first look, I see a lot of similar code between Query and Union. Maybe it's possible to extract that code into a parent class and leave only specific functions into inheritors?

**Comment by jnfeinstein** [comment]
@Tapac I pulled this thread and got stuck when a ton of references require a `Query` reference and not a `AbstractQuery` reference.  That would require a much bigger code change, and I do think using interfaces could benefit the library a lot, specifically for query-like objects.  See potential code below.  Without this you end up with a ton of minor helper functions, which I think ends up being more of a nuisances to maintain.
```kotlin
abstract class AbstractQuery(targets: List<Table>) : SizedIterable<ResultRow>, Statement<ResultSet>(StatementType.SELECT, targets) {
    private val transaction get() = TransactionManager.current()

    var orderByExpressions: List<Pair<Expression<*>, SortOrder>> = mutableListOf()
        private set
    var distinct: Boolean = false
        private set
    var limit: Int? = null
        private set
    var offset: Long = 0
        private set
    var fetchSize: Int? = null
        private set
    abstract val set: FieldSet

    protected fun copyTo(other: AbstractQuery) {
        other.orderByExpressions = orderByExpressions.toMutableList()
        other.distinct = distinct
        other.limit = limit
        other.offset = offset
        other.fetchSize = fetchSize
    }

    override fun PreparedStatementApi.executeInternal(transaction: Transaction): ResultSet? {
        val fetchSize = this@AbstractQuery.fetchSize ?: transaction.db.defaultFetchSize
        if (fetchSize != null) {
            this.fetchSize = fetchSize
        }
        return executeQuery()
    }

    override fun arguments() = QueryBuilder(true).let {
        prepareSQL(it)
        if (it.args.isNotEmpty()) listOf(it.args) else emptyList()
    }

    override fun prepareSQL(transaction: Transaction) = prepareSQL(QueryBuilder(true))

    internal abstract fun prepareSQL(builder: QueryBuilder): String

    fun withDistinct(value: Boolean = true) = apply {
        distinct = value
    }

    override fun limit(n: Int, offset: Long) = apply {
        limit = n
        this.offset = offset
    }

    fun orderBy(column: Expression<*>, order: SortOrder = SortOrder.ASC) = orderBy(column to order)

    override fun orderBy(vararg order: Pair<Expression<*>, SortOrder>) = apply {
        (orderByExpressions as MutableList).addAll(order)
    }

    fun fetchSize(n: Int) = apply {
        fetchSize = n
    }

    override fun iterator(): Iterator<ResultRow> {
        val resultIterator = ResultIterator(transaction.exec(this)!!, set.realFields)
        return if (transaction.db.supportsMultipleResultSets)
            resultIterator
        else {
            Iterable { resultIterator }.toList().iterator()
        }
    }

    protected var count: Boolean = false
        private set

    override fun count(): Long {
        try {
            count = true
            return transaction.exec(this) {
                it.next()
                it.getLong(1)
            }!!
        } finally {
            count = false
        }
    }

    override fun empty(): Boolean {
        val oldLimit = limit
        try {
            limit = 1
            return !transaction.exec(this)!!.next()
        } finally {
            limit = oldLimit
        }
    }
}
```

**Comment by Tapac** [comment]
> I pulled this thread and got stuck when a ton of references require a Query reference and not a AbstractQuery reference. 

It's absolutely normal and it will allow adapting such functions to use UNION where possible step-by-step.
For example, I think that Union should allow to be used as subquery, create aliases for it, etc. But it might be too complicated to make it in a single PR (and not break the current behavior).

**Comment by jnfeinstein** [comment]
Are there any query operations that do not apply to a union?  If not then union should sub-class query.

**Comment by Tapac** [comment]
If you'll inherit from `Query` then functions like `adjustSlice`, `having`, `groupBy` will be also available on `Union` which do not provide such functionality in SQL.
Also, your new `Union.union(other: Query)` will also accept `Union` and that can be unexpected.

**Comment by Tapac** [comment]
@jnfeinstein , why you decided to close a PR? Do you think that my concerns are not valid?

**Comment by jnfeinstein** [comment]
@Tapac totally 100% valid, just don't have time to polish this out right now and I know you have a huge queue of PRs to burn down already.

**Pull request closed without merging**
