### PR TITLE
fix: Verbose logging introduced by LogCaptor

### PR DESCRIPTION
**Pull request by joc-a**
Adding the LogCaptor dependency caused the logging level to be DEBUG instead of INFO, even though it is configured to be INFO in `log4j2.xml`. This is a known issue (https://github.com/Hakky54/log-captor/issues/8) because LogCaptor uses a different appender than the one configured in `log4j2.xml`. More details in this comment: https://github.com/Hakky54/log-captor/issues/8#issuecomment-850676609.

The solution is to remove the dependency and create a custom appender which is used to test the logs.

Partially inspired by [this](https://logging.apache.org/log4j/2.x/manual/customconfig.html#appending-log-events-to-writers-and-outputstreams-programmatical).

### CODE REVIEW

**Comment by Hakky54** [comment]
@joc-a there is a solution for the issue you are facing. You can have logcaptor and mute all of the logs in the console or build output and still do the assertions. I use the following test resource which you can copy over https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/test/resources/logback-test.xml

I was waiting for your input on the issue you created here https://github.com/Hakky54/log-captor/issues/47
However it seems like you already was working on a workaround with a native implementation with log4j2

Do you think it is worth to give it a shot with the logback-test.xml file?

**Comment by joc-a** [comment]
Hey @Hakky54. Thank you for your suggestion. I did try that solution at first after searching through the issues on GitHub, but it won't work for this case because it would completely mute all logs, including those that we would expect to see if there is something being logged that should not be there. I wanted the logging behaviour to be exactly the same as before introducing LogCaptor, meaning that if a bug is reintroduced that causes unwanted logging, we should be able to catch it both by the assertion in the test and by _seeing_ the it in the console.

**Comment by Hakky54** [comment]
I think it should be possible, if you are ok I would like to give it a shot. Can you point out which logs you still want to see and which should not appear?

**Review by e5l — CHANGES_REQUESTED** [review]
Please check https://github.com/JetBrains/Exposed/pull/1852, it looks much simpler

**Comment by joc-a** [comment]
Closing this in favour of #1852

**Pull request closed without merging**
