### PR TITLE
fix: EXPOSED-390 ASC_NULLS_LAST and DESC_NULLS_FIRST for MySQL string columns

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Review by bog-walk — CHANGES_REQUESTED** [review]
Hi @zly2006 Thanks for the PR! Looks good, just need to relocate the new test to a different file.

Could you please instead place the test (and its table) in `shared/dml/OrderByTests.kt`?

**Comment by zly2006** [comment]
> Hi @zly2006 Thanks for the PR! Looks good, just need to relocate the new test to a different file.
> 
> Could you please instead place the test (and its table) in `shared/dml/OrderByTests.kt`?

OK. I assumed that the database keeps the order for string like "b" and "B", gonna remove the lowercase test case.

**Comment by zly2006** [comment]
OK all tests passed https://exposed.teamcity.com/buildConfiguration/Exposed_Build/5920?buildTab=tests&focusLine=NaN&name=testNullableStringOrdering

**Review by bog-walk — APPROVED** [review]
Thanks again @zly2006, and also for adapting the test to fit all supported databases.

**Comment by zly2006** [comment]
@bog-walk i have adopted these test. please see the build log, the unit tests passed on all databases.

**Pull request merged**
