### PR TITLE
Add support for 'insertIgnore' and 'deleteIgnore' in SQLite

### PR DESCRIPTION
**Pull request by SackCastellon**
Added support for 'insertIgnore' and 'deleteIgnore' in SQLite based on the [official documentation](https://sqlite.org/lang_conflict.html)

### CODE REVIEW

**Comment by Tapac** [comment]
Could you, please, adjust `DMLTest.testInsertIgnoreAndGetId01` test to also test SQLite, not only Mysql?

**Comment by Tapac** [comment]
Looks like test failed https://teamcity.jetbrains.com/viewLog.html?buildId=1345844&tab=buildResultsDiv&buildTypeId=Exposed_PullRequests

**Comment by SackCastellon** [comment]
I have done some research and it seems like the way the SQLite JDBC retrieves the _generated keys_ is by executing the query `select last_insert_rowid();` which returns the **row id of the _last successfully_ inserted row** meaning that if run the following query:
```sql
CREATE TABLE IF NOT EXISTS tmp (id INTEGER PRIMARY KEY, foo VARCHAR(10) NOT NULL);
CREATE UNIQUE INDEX tmp_foo_unique ON tmp (foo);

INSERT OR IGNORE INTO tmp (foo) VALUES ('1');
SELECT last_insert_rowid(); # Returns: 1
INSERT OR IGNORE INTO tmp (foo) VALUES ('2');
SELECT last_insert_rowid(); # Returns: 2
INSERT OR IGNORE INTO tmp (foo) VALUES ('3');
SELECT last_insert_rowid(); # Returns: 3
INSERT OR IGNORE INTO tmp (foo) VALUES ('2');
SELECT last_insert_rowid(); # Returns: 3
```
Even though the last insert failed (was ignored), the query `select last_insert_rowid();` still returns a row id, which happens to be the id of the previous insert, which was successful.

This behaviour is also explained in the [_SQLite C Interface_ official documentation](https://www.sqlite.org/c3ref/last_insert_rowid.html)

Finally, I think that this is a problem because it doesn't follow what the JavaDoc for the [`Satement.getGeneratedKeys()`](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#getGeneratedKeys--) says which states that:
> If this `Statement` object did not generate any keys, an empty `ResultSet` object is returned.

**Comment by Tapac** [comment]
I think that there is also issue in Exposed's `InsertStatement.processResults` function, which shouldn't iterate over result set if no rows were updated. I've just committed a fix for it and all tests (including yours) were passed. 

So I'll merge your PR (but will keep in mind about that "SQLite specific")

**Pull request merged**
