### PR TITLE
Issue #934 (https://github.com/JetBrains/Exposed/issues/934)

### PR DESCRIPTION
**Pull request by freedom4live**
Fix foreign key creation in PostgreSQL

### CODE REVIEW

**Comment by Tapac** [comment]
@freedom4live, could you please check failed MySQL tests?
https://teamcity.jetbrains.com/viewType.html?buildTypeId=Exposed_PullRequests&branch_Exposed=936%2Fmerge&tab=buildTypeStatusDiv

**Comment by freedom4live** [comment]
@Tapac The tests can't connect to the database on the Windows Build Agent. I'm pretty sure that it's not related to my changes. Seems like something wrong with configuration? Could you help with it?

**Comment by Tapac** [comment]
@freedom4live , I'll take a look on this (as I run tests on Windows locally), but there are two tests still failing (https://teamcity.jetbrains.com/viewLog.html?buildId=2959998&buildTypeId=Exposed_PullRequests)

**Comment by freedom4live** [comment]
Updated master from upstream. https://teamcity.jetbrains.com/viewLog.html?buildId=2963118&buildTypeId=Exposed_PullRequests 
Now see problems with DB connection only :(

**Pull request merged**
