### PR TITLE
Detect column casing name change SchemaUtils.addMissingColumnsStateme…

### PR DESCRIPTION
**Pull request by spand**
…nts()

### CODE REVIEW

**Comment by Tapac** [comment]
Hi @spand , can you please merge the current master into the branch?
I think that `Triple` should be replaced with some internal data class

**Comment by spand** [comment]
> 
> 
> Hi @spand , can you please merge the current master into the branch? I think that `Triple` should be replaced with some internal data class

I will take a look.

**Comment by spand** [comment]
> 
> 
> Hi @spand , can you please merge the current master into the branch? I think that `Triple` should be replaced with some internal data class

I have pushed two new rebased commits.
1) One introducing the ColumnDiff change as you requested. It is not internal since its used in public methods but I cant see much of a problem with it being public as it turned out.
2) The original change.

**Comment by spand** [comment]
@Tapac  I will take a look at the failed build

**Comment by spand** [comment]
@Tapac Ready for another go.

**Comment by spand** [comment]
Thanks for fixing the last of it @Tapac ! Got caught up in some other work.

**Pull request merged**
