### PR TITLE
Issue 221 - Map `java.time.Instant` to type stored in UTC

### PR DESCRIPTION
**Pull request by tnleeuw**
Related issue: https://github.com/JetBrains/Exposed/issues/221

Use a `timestamp with timezone` to store `java.time.Instant` in UTC where possible; for MySQL use `timestamp` type which always stores data in UTC.

Works in Progress.

### CODE REVIEW

**Comment by tnleeuw** [comment]
Unit tests failed when I pushed change to remove version-nr update. They passed before that. I will see if I can find out why that is but of course I do not want to merge a change tot the version-nr; perhaps I should rebase on master instead of having branched off of the release 0.31.1 version!

**Comment by Tapac** [comment]
@tnleeuw , hi, can you please check `MiscTableTest.testUpdate02` fails on mysql. 
[Failed build](https://teamcity.jetbrains.com/viewLog.html?buildId=3573393&buildTypeId=Exposed_PullRequests)

**Comment by tnleeuw** [comment]
> @tnleeuw , hi, can you please check `MiscTableTest.testUpdate02` fails on mysql.
> [Failed build](https://teamcity.jetbrains.com/viewLog.html?buildId=3573393&buildTypeId=Exposed_PullRequests)

Hi,

Thanks for having a look at the PR!
I will have a look at the failing tests, hopefully tomorrow.

**Comment by hfhbd** [comment]
This current behavior is very strange! 
@tnleeuw Please add also `TIMESTAMPTZ` in `PostgreSQLDialect`.

**Comment by joc-a** [comment]
Hey @tnleeuw. Thank you for your contribution. This feature has now been implemented here #1787.

**Comment by tnleeuw** [comment]
> Hey @tnleeuw. Thank you for your contribution. This feature has now been implemented here #1787.

I'm afraid I have not contributed all that much, I never managed to fix unit tests for all supported databases!

**Pull request closed without merging**
